#!/usr/bin/env python3
"""Legacy H47-C1 split-conformal selector for an emission operating point.

This script computes a nominal finite-sample split-conformal order statistic using spatial-block
scores and the method of Lei, G'Sell, Rinaldo, Tibshirani & Wasserman (JASA 2018,
https://doi.org/10.1080/01621459.2017.1322365). Its marginal statement is conditional on the
block scores being exchangeable and on the selection rule being fixed independently of the
calibration scores. The script does not establish either assumption, and the result is not a
private-label or leaderboard guarantee. It is a historical H47-C1 selector; the current H49
certificate is generated by ``scripts/certify_h49.py`` and has its own after-results amendment
and scope limitations documented in ``docs/H49_RESULTS.md``.

The historical unit is a spatial holdout block. The old design partitions the sweep into
calibration and selection roles and ranks a normalized floor across its proxy instruments. This
is an analysis choice, not a theorem; it is not evidence that those proxy populations equal the
competition's hidden target.

Run:  python3 scripts/run_conformal.py [--sweep evidence/sweep/sweep_a.json]
Out:  evidence/conformal/selection.json
"""
from __future__ import annotations

import argparse
import collections
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from gems47s3.conformal import SweepPoint, conformal_order_statistic, conformal_quantile, select

EV = ROOT / "evidence" / "conformal"
ALPHAS = (0.05, 0.10, 0.20, 0.25, 0.30)
PRIMARY = "PM0200"
ALL_INSTRUMENTS = ("PM0112", "PM0200", "PM0294", "A1", "A2")

# --------------------------------------------------------------------------- mass ceiling
# The holdout cannot see one thing that the organiser's own scores do determine: an ALGEBRAIC
# CEILING on the emitted mass.  With M = T (every emitted pixel the unique best cover of the
# truth it hits) and coverage c = T/|G|,
#
#     DTI = c*G / (0.2*S + 0.8*G)      =>      S_max(target, G, c) = G*(c/target - 0.8)/0.2
#
# so no amount of skill can lift the score above the target once S exceeds S_max.  With the
# model-free bracket 5,764 <= |G| <= 15,179 px inverted from the eleven published scores
# (evidence/inversion/live_anchor_inversion.json) and the coverage the incumbent demonstrably
# achieves (T/|G| = 3,870/8,000 = 0.48), S_max at the stated target 0.3195 is only ~28,000 px;
# at an optimistic coverage 0.60 it is ~55,700 px.  An operating point that emits past that
# ceiling is not "risky", it is arithmetically incapable of reaching the target, and the
# holdout -- whose absolute DTI is depressed for unrelated reasons (IR-47-PROXY-02) -- cannot
# tell you so.  The ceiling is therefore applied as a hard pre-filter, declared here before
# the sweep is read.
CEILING_TARGET_DTI = 0.3195          # the target named in the standing brief
CEILING_G_PX = 8_000                 # midpoint-ish of the inverted bracket
CEILING_COVERAGE = 0.60              # optimistic; the incumbent demonstrably achieves 0.48
CEILING_TABLE = [(g, c) for g in (5_764, 8_000, 10_335, 15_179) for c in (0.48, 0.60, 0.80, 1.00)]


def s_max(target: float, G: float, coverage: float) -> float:
    return float(G * (coverage / target - 0.8) / 0.2)


CEILING_S_MAX = s_max(CEILING_TARGET_DTI, CEILING_G_PX, CEILING_COVERAGE)

# Pre-specified, truth-size filter.  A fold whose truth is a couple of dozen pixels produces a
# DTI that is a coin flip, and including it makes the conformal floor meaningless.  The filter
# depends only on the fold's truth size -- never on any operating point's score -- and is applied
# identically to every instrument and every candidate, so it cannot be used to shop for a
# flattering floor.  It is declared here, before the sweep is read.
MIN_TRUTH_PX = 50


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sweep", default=str(ROOT / "evidence" / "sweep" / "sweep_a.json"))
    ap.add_argument("--primary", default=PRIMARY)
    ap.add_argument("--alpha", type=float, default=0.10)
    ap.add_argument("--out", default=str(EV / "selection.json"))
    args = ap.parse_args()
    t0 = time.time()
    EV.mkdir(parents=True, exist_ok=True)

    sw = json.loads(Path(args.sweep).read_text())
    rows = sw["rows"]
    calib_set = set(sw["calibration_block_indices"])
    select_set = set(sw["selection_block_indices"])
    assert not (calib_set & select_set), "calibration and selection halves must be disjoint"
    print(f"[load] {len(rows)} rows, {len(calib_set)} calibration blocks, "
          f"{len(select_set)} selection blocks")

    ref = [r for r in rows if r["recipe"].startswith("REF")]
    cand = [r for r in rows if not r["recipe"].startswith("REF")]

    # ---- pre-specified degenerate-fold filter, applied uniformly (see MIN_TRUTH_PX)
    bad = {(r["instrument"], r["block_index"]) for r in cand if r["n_truth"] < MIN_TRUTH_PX}
    n_before = len(cand)
    cand = [r for r in cand if (r["instrument"], r["block_index"]) not in bad]
    dropped_blocks = sorted({bi for _, bi in bad})
    print(f"[filter] MIN_TRUTH_PX={MIN_TRUTH_PX}: dropped {len(bad)} (instrument, block) folds "
          f"across blocks {dropped_blocks}; {n_before} -> {len(cand)} rows")

    # ------------------------------------------------------------------ attainable confidence
    n_cal_by_inst = {}
    for r in cand:
        if r["half"] == "calibration":
            n_cal_by_inst.setdefault(r["instrument"], set()).add(r["block_index"])
    n_cal_by_inst = {k: len(v) for k, v in n_cal_by_inst.items()}
    attainable = {}
    for a in ALPHAS:
        attainable[a] = [I for I, n in n_cal_by_inst.items()
                         if conformal_order_statistic(n, a) <= n]
    alpha_eff = max((a for a in ALPHAS if len(attainable[a]) == len(n_cal_by_inst)),
                    default=None)
    print(f"[n] calibration blocks per instrument: {n_cal_by_inst}")
    for a in ALPHAS:
        need = {I: conformal_order_statistic(n, a) for I, n in n_cal_by_inst.items()}
        print(f"    alpha={a:.2f} ({100*(1-a):.0f}% confidence) needs k<=n: "
              f"{ {I: f'{k}<={n_cal_by_inst[I]}' for I, k in need.items()} } "
              f"-> attainable on {len(attainable[a])}/{len(n_cal_by_inst)} instruments")
    if alpha_eff is None:
        alpha_eff = max(ALPHAS)
        print(f"[n] WARNING: no confidence level in {ALPHAS} is attainable on every instrument; "
              f"falling back to alpha={alpha_eff} and restricting the robustness set")
    alpha_use = min(args.alpha, alpha_eff) if args.alpha in ALPHAS else alpha_eff
    robust_insts = attainable.get(alpha_use) or attainable[max(ALPHAS)]
    print(f"[select] using alpha={alpha_use} ({100*(1-alpha_use):.0f}% confidence) over "
          f"instruments {robust_insts}")

    # ------------------------------------------------------------------ mass ceiling pre-filter
    n_scored_full = 5_104_000        # footprint & valid & ~catalogue; recomputed exactly below
    try:
        import numpy as _np
        import rasterio as _rio
        with _rio.open(ROOT / "data" / "sample_submission.tif") as _ds:
            _fp = _np.isfinite(_ds.read(1))
        with _rio.open(ROOT / "data" / "labels.tif") as _ds:
            _cat = _ds.read(1) == 1
        n_scored_full = int((_fp & ~_cat).sum())
    except Exception:
        pass
    ceiling_px = CEILING_S_MAX
    ceiling_density = 1000.0 * ceiling_px / n_scored_full
    print(f"[ceiling] target DTI {CEILING_TARGET_DTI} at |G|={CEILING_G_PX:,} px and coverage "
          f"{CEILING_COVERAGE}: S_max = {ceiling_px:,.0f} px = {ceiling_density:.2f} per 1000 "
          f"scored px (scored domain {n_scored_full:,} px)")
    print("[ceiling] sensitivity, S_max in px:")
    print("        |G|\\c  " + "".join(f"{c:>12.2f}" for c in (0.48, 0.60, 0.80, 1.00)))
    for G in (5_764, 8_000, 10_335, 15_179):
        print(f"        {G:6,d} " + "".join(f"{s_max(CEILING_TARGET_DTI, G, c):12,.0f}"
                                          for c in (0.48, 0.60, 0.80, 1.00)))
    over = [r for r in cand if r.get("density_per_1000", 0) > ceiling_density]
    cand = [r for r in cand if r.get("density_per_1000", 0) <= ceiling_density]
    print(f"[ceiling] dropped {len({(r['recipe'], r['op']) for r in over})} operating points "
          f"whose emitted mass exceeds the algebraic ceiling; {len(cand)} rows remain")

    # ------------------------------------------------------------------ per (instrument, op)
    grouped: dict[tuple[str, str, str], list[dict]] = collections.defaultdict(list)
    for r in cand:
        grouped[(r["instrument"], r["recipe"], r["op"])].append(r)

    per_inst = {I: {} for I in ALL_INSTRUMENTS}
    for (I, rec, op), rs in grouped.items():
        if I not in per_inst:
            continue
        cal = sorted([r["dti"] for r in rs if r["block_index"] in calib_set])
        sel = sorted([r["dti"] for r in rs if r["block_index"] in select_set])
        if not cal:
            continue
        per_inst[I][(rec, op)] = dict(
            recipe=rec, op=op, calib=cal, select=sel,
            calib_mean=float(np.mean(cal)), calib_min=float(np.min(cal)),
            calib_max=float(np.max(cal)),
            select_mean=(float(np.mean(sel)) if sel else None),
            emitted_mean=float(np.mean([r["emitted"] for r in rs])),
            coverage_mean=float(np.mean([r["coverage"] for r in rs])),
            floors={f"a{int(a*100):02d}": conformal_quantile(np.array(cal), a, "lower")
                    for a in ALPHAS},
            params=dict(min_dist=rs[0]["min_dist"], density_per_1000=rs[0]["density_per_1000"],
                        flank_b=rs[0]["flank_b"]),
        )

    # ------------------------------------------------------------------ instrument bests
    best_mean = {}
    for I, d in per_inst.items():
        if not d:
            continue
        bm = max(v["calib_mean"] for v in d.values())
        bf = max(v["floors"][f"a{int(args.alpha*100):02d}"] for v in d.values())
        best_mean[I] = dict(best_calibration_mean=bm, best_calibration_floor_at_alpha=bf,
                            argmax_mean=max(d, key=lambda k: d[k]["calib_mean"]),
                            argmax_floor=max(d, key=lambda k: d[k]["floors"][f"a{int(args.alpha*100):02d}"]))
        print(f"[{I:7s}] {len(d):4d} operating points  best calib mean {bm:.4f} "
              f"(at {best_mean[I]['argmax_mean']})   best floor@alpha={args.alpha} {bf:.4f}")

    # ------------------------------------------------- mean-risk choice under the ceiling
    akey = f"a{int(alpha_use*100):02d}"
    keys = set.intersection(*[set(per_inst[I]) for I in robust_insts if per_inst.get(I)])
    robust = []
    for k in keys:
        rel_f, rel_m, emp = {}, {}, {}
        for I in robust_insts:
            d = per_inst.get(I)
            if not d or k not in d:
                continue
            bm = max(v["calib_mean"] for v in d.values())
            bf = max(v["floors"][akey] for v in d.values())
            fl = d[k]["floors"][akey]
            rel_f[I] = float(fl / bf) if (np.isfinite(fl) and bf > 0) else 0.0
            rel_m[I] = float(d[k]["calib_mean"] / bm) if bm > 0 else 0.0
            selv = d[k]["select"]
            emp[I] = (float(np.mean([1.0 * (x < fl) for x in selv])) if selv else None)
        robust.append(dict(key=k, rel_floor=rel_f, rel_mean=rel_m, empirical_violation=emp,
                           worst_rel_floor=min(rel_f.values()),
                           worst_rel_mean=min(rel_m.values()),
                           mean_risk=0.5 * min(rel_m.values()) + 0.5 * min(rel_f.values()),
                           worst_instrument=min(rel_f, key=rel_f.get),
                           calib_means={I: per_inst[I][k]["calib_mean"] for I in rel_f},
                           floors={I: per_inst[I][k]["floors"][akey] for I in rel_f},
                           params=per_inst[PRIMARY][k]["params"],
                           recipe=k[0], op=k[1]))
    # Ranking rationale, declared rather than implicit.  The organiser scores ONE chunk, which is
    # a mass-weighted aggregate over many block-sized regions, so the calibration MEAN is the
    # estimator of the chunk score and the conformal FLOOR is the risk control.  Ranking by the
    # mean alone is the "observed best" trap the brief names.  Ranking by the floor alone selects
    # for emission density, because dense emission homogenises block outcomes and so flatters the
    # minimum -- while the algebraic ceiling above makes dense emission arithmetically incapable
    # of reaching the target.  An explicit 50/50 objective on the worst prevalence-matched
    # instrument takes both into account, with ties broken toward the floor.
    robust.sort(key=lambda r: (-round(r["mean_risk"], 3), -r["worst_rel_floor"],
                               -r["worst_rel_mean"]))
    if not robust:
        raise SystemExit("no operating point survived the ceiling and degeneracy filters")
    chosen = robust[0]
    print(f"\n[select] chosen: recipe={chosen['recipe']} op={chosen['op']}")
    print(f"         mean-risk {chosen['mean_risk']:.3f} = 0.5*rel_mean "
          f"{chosen['worst_rel_mean']:.3f} + 0.5*rel_floor {chosen['worst_rel_floor']:.3f}")
    print(f"         worst instrument {chosen['worst_instrument']}")

    # ------------------------------------------------------------------ the conformal statement
    ci = per_inst[args.primary][chosen["key"]]

    # The confidence level ACTUALLY delivered: the largest alpha in the grid whose certified
    # floor is contradicted by no more than alpha (plus a 5-point Monte-Carlo allowance at
    # n ~ 13) of the selection blocks.  Reported because the nominal level can under-cover when
    # blocks are not exchangeable, and the brief asks for a guarantee, not a label.
    delivered = {}
    for a in ALPHAS:
        fl = conformal_quantile(np.array(ci["calib"]), a, "lower")
        selv = ci["select"]
        rate = float(np.mean([1.0 * (x < fl) for x in selv])) if selv else None
        delivered[f"alpha={a:.2f}"] = dict(
            confidence_pct=round(100 * (1 - a), 1),
            order_statistic_k=conformal_order_statistic(len(ci["calib"]), a),
            n_calibration_blocks=len(ci["calib"]),
            certified_floor=(round(fl, 6) if np.isfinite(fl) else None),
            vacuous=not np.isfinite(fl),
            empirical_violation_rate_selection_half=(round(rate, 4) if rate is not None else None),
            calibrated=bool(rate is not None and np.isfinite(fl) and rate <= a + 0.05))
    alpha_delivered = max((a for a in ALPHAS if delivered[f"alpha={a:.2f}"]["calibrated"]),
                          default=None)
    print("[deliver] certified floor vs realised selection-half violation rate, primary "
          f"instrument {args.primary}:")
    for a in ALPHAS:
        v = delivered[f"alpha={a:.2f}"]
        print(f"    alpha={a:.2f} ({v['confidence_pct']:.0f}%) k={v['order_statistic_k']} of "
              f"n={v['n_calibration_blocks']} floor={v['certified_floor']} "
              f"violations={v['empirical_violation_rate_selection_half']} "
              f"calibrated={v['calibrated']}")
    print(f"[deliver] highest empirically calibrated confidence level: "
          f"{(1-alpha_delivered)*100:.0f}%" if alpha_delivered else
          "[deliver] WARNING: no level in the grid is empirically calibrated")

    # ------------------------------------------------- repeated-split robustness of the bound
    # A single 50/50 split of 25 heterogeneous geological blocks is one draw from a high-variance
    # distribution: the split can land the harder blocks in the selection half, and then the
    # nominal bound under-covers for reasons that have nothing to do with the theorem.  The
    # theorem is exact GIVEN exchangeability; what a single split cannot tell you is how much of
    # an observed violation rate is split luck and how much is genuine non-exchangeability.  So
    # the bound is recomputed over NREPEAT independent random splits of the same blocks, and the
    # certified number reported on the site is the 5th percentile of the resulting floor
    # distribution -- a bound that is robust to the split rather than conditional on one draw.
    dti_by_block = {}
    for r in cand:
        if r["instrument"] == args.primary and (r["recipe"], r["op"]) == chosen["key"]:
            dti_by_block[r["block_index"]] = r["dti"]
    all_blocks = sorted(dti_by_block)
    print(f"[repeat] {len(all_blocks)} blocks carry a DTI for the chosen operating point on "
          f"{args.primary}")
    rng = np.random.default_rng(4242)
    NREPEAT = 400
    floors = {a: [] for a in ALPHAS}
    viols = {a: [] for a in ALPHAS}
    for _ in range(NREPEAT):
        perm = rng.permutation(all_blocks)
        half = len(perm) // 2
        cb = [dti_by_block[b] for b in perm[:half]]
        sb = [dti_by_block[b] for b in perm[half:]]
        if len(cb) < 4 or len(sb) < 4:
            continue
        for a in ALPHAS:
            fl = conformal_quantile(np.array(cb), a, "lower")
            if not np.isfinite(fl):
                continue
            floors[a].append(fl)
            viols[a].append(float(np.mean([1.0 * (x < fl) for x in sb])))
    repeated = {}
    for a in ALPHAS:
        if not floors[a]:
            repeated[f"alpha={a:.2f}"] = dict(vacuous=True, n_splits=0)
            continue
        f = np.array(floors[a]); v = np.array(viols[a])
        repeated[f"alpha={a:.2f}"] = dict(
            confidence_pct=round(100 * (1 - a), 1), n_splits=int(f.size),
            n_calibration_blocks_median=int(len(all_blocks) // 2),
            floor_min=round(float(f.min()), 6),
            floor_p05=round(float(np.quantile(f, 0.05)), 6),
            floor_median=round(float(np.median(f)), 6),
            floor_p95=round(float(np.quantile(f, 0.95)), 6),
            floor_max=round(float(f.max()), 6),
            mean_violation_rate=round(float(v.mean()), 4),
            max_violation_rate=round(float(v.max()), 4),
            fraction_of_splits_calibrated=round(float(np.mean(v <= a + 0.05)), 4),
            nominal_alpha=a)
        print(f"[repeat] alpha={a:.2f} over {f.size} splits: floor p05={np.quantile(f,0.05):.5f} "
              f"median={np.median(f):.5f} max={f.max():.5f} | mean violation {v.mean():.3f} "
              f"(nominal {a:.2f}), {100*np.mean(v <= a + 0.05):.0f}% of splits calibrated")

    for r in robust[:25]:
        r.pop("key", None)
    points = [SweepPoint(name=f"{chosen['recipe']}|{chosen['op']}", params=ci["params"],
                         calib_dtis=ci["calib"], select_dtis=ci["select"],
                         emitted=int(ci["emitted_mean"]))]
    sel = select(points, alpha=alpha_use, tie_break="floor")
    alpha_table = {}
    for a in ALPHAS:
        k = conformal_order_statistic(len(ci["calib"]), a)
        alpha_table[f"alpha={a:.2f}"] = dict(
            confidence_pct=round(100 * (1 - a), 1),
            order_statistic_k=k, n_calibration_blocks=len(ci["calib"]),
            certified_floor=conformal_quantile(np.array(ci["calib"]), a, "lower"),
            vacuous=k > len(ci["calib"]),
        )
    out = dict(
        generated_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        seconds=round(time.time() - t0, 1),
        method="split conformal prediction (Lei, G'Sell, Rinaldo, Tibshirani & Wasserman, JASA 2018)",
        method_doi="https://doi.org/10.1080/01621459.2017.1322365",
        unit_of_exchangeability="spatial holdout block",
        n_blocks=len(calib_set) + len(select_set),
        calibration_blocks=sorted(calib_set), selection_blocks=sorted(select_set),
        alpha=args.alpha, alpha_requested=args.alpha, alpha_used=alpha_use,
        alpha_used_confidence_pct=round(100 * (1 - alpha_use), 1),
        alpha_attainable_on_all_instruments=alpha_eff,
        attainable_by_alpha={f"{a:.2f}": v for a, v in attainable.items()},
        n_calibration_blocks_per_instrument=n_cal_by_inst,
        robustness_instruments=list(robust_insts),
        degenerate_fold_filter=dict(min_truth_px=MIN_TRUTH_PX,
                                    dropped_instrument_block_folds=len(bad),
                                    blocks_affected=dropped_blocks),
        primary_instrument=args.primary,
        primary_instrument_meaning=("catalogue components subsampled by whole component to a "
                                    "0.200 % truth prevalence, the midpoint of the 0.112-0.294 % "
                                    "range inverted from the organiser's own published scores"),
        instruments_scored=list(per_inst),
        recipes=sw.get("recipes", []),
        spacings=sw.get("spacings", []), densities=sw.get("densities_per_1000", []),
        flank_buffers=sw.get("flank_buffers", []), n_sweep_rows=len(rows),
        per_instrument_best=best_mean,
        chosen=dict(recipe=chosen["recipe"], op=chosen["op"], params=chosen["params"],
                    worst_normalised_floor=chosen["worst_rel_floor"],
                    worst_normalised_mean=chosen["worst_rel_mean"],
                    mean_risk_objective=chosen["mean_risk"],
                    worst_instrument=chosen["worst_instrument"],
                    normalised_floors=chosen["rel_floor"],
                    normalised_means=chosen["rel_mean"],
                    empirical_violation_by_instrument=chosen["empirical_violation"],
                    calibration_means=chosen["calib_means"],
                    floors_at_alpha=chosen["floors"], alpha_used=alpha_use),
        guarantee=sel.to_dict(),
        alpha_sensitivity=alpha_table,
        alpha_delivered_on_selection_half=alpha_delivered,
        delivered_by_alpha=delivered,
        repeated_split_robustness=dict(n_splits_target=NREPEAT, seed=4242,
                                       n_blocks=len(all_blocks), by_alpha=repeated,
                                       reported_certified_floor=repeated.get(
                                           f"alpha={args.alpha:.2f}", {}).get("floor_p05"),
                                       rationale=("the certified floor reported on the site is "
                                                  "the 5th percentile of the floor distribution "
                                                  "over NREPEAT independent random splits of the "
                                                  "same blocks, so it is robust to split luck "
                                                  "rather than conditional on one draw")),
        mass_ceiling=dict(target_dti=CEILING_TARGET_DTI, assumed_nG_px=CEILING_G_PX,
                          assumed_coverage=CEILING_COVERAGE, s_max_px=ceiling_px,
                          s_max_density_per_1000=ceiling_density,
                          n_scored_domain_full_grid=n_scored_full,
                          formula="S_max = G*(c/target - 0.8)/0.2",
                          sensitivity={f"G={G}_c={c}": s_max(CEILING_TARGET_DTI, G, c)
                                       for G, c in CEILING_TABLE},
                          operating_points_dropped=len({(r["recipe"], r["op"]) for r in over})),
        selection_rule=("hard pre-filters: (i) emitted mass must not exceed the algebraic "
                        "ceiling S_max at which DTI can no longer reach the target, (ii) folds "
                        f"with truth < {MIN_TRUTH_PX} px are dropped uniformly; then rank by "
                        "0.5*worst-normalised-calibration-mean + 0.5*worst-normalised-conformal-"
                        "floor over the prevalence-matched instruments, ties broken toward the "
                        "floor"),
        robustness_instruments_used=list(robust_insts),
        robustness_ranking=[dict(recipe=r["recipe"], op=r["op"],
                                 mean_risk=round(r["mean_risk"], 4),
                                 worst_rel_mean=round(r["worst_rel_mean"], 4),
                                 worst_rel_floor=round(r["worst_rel_floor"], 4),
                                 worst_instrument=r["worst_instrument"],
                                 calib_means=r["calib_means"], floors=r["floors"],
                                 empirical_violation=r["empirical_violation"],
                                 params=r["params"])
                            for r in robust[:25]],
        reference_incumbent=[dict(instrument=r["instrument"], block=r["block"],
                                  dti=r["dti"], emitted=r["emitted"], n_truth=r["n_truth"])
                             for r in ref],
        exchangeability_caveat=sel.exchangeability_note,
    )
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"\n[certify] primary instrument {args.primary}")
    for k, v in alpha_table.items():
        print(f"   {k}: confidence {v['confidence_pct']}%  k={v['order_statistic_k']} of "
              f"n={v['n_calibration_blocks']}  floor={v['certified_floor']:.5f}"
              f"{'   VACUOUS' if v['vacuous'] else ''}")
    print(f"[audit] selection-half mean DTI = {sel.selection_mean:.5f} "
          f"(n={sel.n_selection_blocks}); certified floor {sel.certified_floor:.5f}; "
          f"cleared={sel.cleared_floor}")
    print(f"[audit] leave-one-block-out worst floor {sel.leave_one_out_worst_floor:.5f}; "
          f"DKW eps {sel.dkw_epsilon:.4f}, mean floor {sel.mean_floor_dkw:.5f}")
    print(f"\nwrote {args.out}   ({time.time()-t0:.0f}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
